[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "python-telegram-bot>=20.0",
    "pytz>=2025.2",
    "telegram>=0.0.1",
]
